package com.example.bawei.com.movies.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.bawei.com.movies.bean.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Long> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property NickName = new Property(0, String.class, "nickName", false, "NICK_NAME");
        public final static Property Phone = new Property(1, String.class, "phone", false, "PHONE");
        public final static Property Birthday = new Property(2, long.class, "birthday", false, "BIRTHDAY");
        public final static Property Sex = new Property(3, int.class, "sex", false, "SEX");
        public final static Property LastLoginTime = new Property(4, long.class, "lastLoginTime", false, "LAST_LOGIN_TIME");
        public final static Property HeadPic = new Property(5, String.class, "headPic", false, "HEAD_PIC");
        public final static Property UserId = new Property(6, long.class, "userId", true, "_id");
        public final static Property SessionId = new Property(7, String.class, "sessionId", false, "SESSION_ID");
    }


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"NICK_NAME\" TEXT," + // 0: nickName
                "\"PHONE\" TEXT," + // 1: phone
                "\"BIRTHDAY\" INTEGER NOT NULL ," + // 2: birthday
                "\"SEX\" INTEGER NOT NULL ," + // 3: sex
                "\"LAST_LOGIN_TIME\" INTEGER NOT NULL ," + // 4: lastLoginTime
                "\"HEAD_PIC\" TEXT," + // 5: headPic
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 6: userId
                "\"SESSION_ID\" TEXT);"); // 7: sessionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(1, nickName);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(2, phone);
        }
        stmt.bindLong(3, entity.getBirthday());
        stmt.bindLong(4, entity.getSex());
        stmt.bindLong(5, entity.getLastLoginTime());
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(6, headPic);
        }
        stmt.bindLong(7, entity.getUserId());
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(8, sessionId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(1, nickName);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(2, phone);
        }
        stmt.bindLong(3, entity.getBirthday());
        stmt.bindLong(4, entity.getSex());
        stmt.bindLong(5, entity.getLastLoginTime());
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(6, headPic);
        }
        stmt.bindLong(7, entity.getUserId());
 
        String sessionId = entity.getSessionId();
        if (sessionId != null) {
            stmt.bindString(8, sessionId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 6);
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // nickName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // phone
            cursor.getLong(offset + 2), // birthday
            cursor.getInt(offset + 3), // sex
            cursor.getLong(offset + 4), // lastLoginTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // headPic
            cursor.getLong(offset + 6), // userId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // sessionId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setNickName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPhone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBirthday(cursor.getLong(offset + 2));
        entity.setSex(cursor.getInt(offset + 3));
        entity.setLastLoginTime(cursor.getLong(offset + 4));
        entity.setHeadPic(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUserId(cursor.getLong(offset + 6));
        entity.setSessionId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInfo entity, long rowId) {
        entity.setUserId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
